# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        
      - name: Print ENV
        run: |
          echo outputname:$outputname
          echo outputpath:$outputpath
        
      - uses: actions/upload-artifact@v3
        with:
          name: ${{env.outputname}}
          path: ${{env.outputpath}}

# git remote add upstream https://github.com/LSPosed/MagiskOnWSALocal
# git fetch upstream
# git rebase upstream/main
# git push --force

# cd scripts
# ./run.sh
# cd ../output
# echo outputname=$(ls) >> $GITHUB_ENV
# echo outputpath=$(pwd)/$(ls) >> $GITHUB_ENV
# touch /tmp/continue